version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "30 0 * * 2"
    groups:
      deps:
        patterns:
          - "actions*"
      tools:
        patterns:
          - "azure*"
    commit-message:
      prefix: "[GitHub Actions Dependency Update]"
    open-pull-requests-limit: 10
    target-branch: "github-actions"
    labels:
      - "github-actions"
      - "dependabot"
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "cron"
      cronjob: "30 12 * * 2"
    groups:
      deps:
        patterns:
          - "@azure/*"
          - "applicationinsights"
          - "cors"
          - "dotenv"
          - "express"
          - "helmet"
          - "mongoose"
      tools:
        patterns:
          - "nodemon"
    commit-message:
      prefix: "[npm Dependency Update (Backend)]"
    open-pull-requests-limit: 10
    target-branch: "dev"
    labels:
      - "npm"
      - "dependabot"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "cron"
      cronjob: "30 12 * * 2"
    groups:
      deps:
        patterns:
          - "@popperjs/*"
          - "bootstrap"
          - "react"
          - "react-*"
          - "vite"
          - "vite-*"
      tools:
        patterns:
          - "@eslint/*"
          - "@vite/*"
          - "eslint"
          - "eslint-*"
    commit-message:
      prefix: "[npm Dependency Update (Frontend)]"
    open-pull-requests-limit: 10
    target-branch: "dev"
    labels:
      - "npm"
      - "dependabot"
