name: Frontend Updates (main branch)

on:
    pull_request:
        types:
            - closed
        branches:
            - main
        paths:
            - "frontend/**"
            - "shared/**"
    workflow_dispatch:

env:
    AZURE_WEBAPP_NAME: "itadakistreetseriesanalyzer"
    AZURE_WEBAPP_PACKAGE_PATH: "."
    NODE_VERSION: "24.x"
    BRANCH_NAME: "main"
    DIRECTORY_NAME: "frontend"

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v7

            - name: Set up Node.js
              uses: actions/setup-node@v7
              with:
                node-version: ${{ env.NODE_VERSION }}
                cache: "npm"
                cache-dependency-path: ${{ env.DIRECTORY_NAME }}/package-lock.json

            - name: npm install, build, and test
              working-directory: ${{ env.DIRECTORY_NAME }}
              run: |
                npm install
                npm run build --if-present
                npm run test --if-present

            - name: Copy environment files
              run: |
                cp ${{ env.DIRECTORY_NAME }}/src/environmentfiles/${{ env.BRANCH_NAME }}/robots.txt ${{ env.DIRECTORY_NAME }}/dist/robots.txt

            - name: Copy shared files
              run: |
                cp -r shared ${{ env.DIRECTORY_NAME }}/src/shared

            - name: Upload artifact to deploy job
              uses: actions/upload-artifact@v7
              with:
                name: node-app-${{ env.BRANCH_NAME }}
                path: ${{ env.DIRECTORY_NAME }}/dist

    deploy:
        permissions:
            contents: none
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        if: github.actor != 'dependabot[bot]'
        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v8
              with:
                name: node-app-${{ env.BRANCH_NAME }}

            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v3
              with:
                app-name: ${{ env.AZURE_WEBAPP_NAME }}
                publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_MAIN }}
                package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
